{application,rores,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{rores_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[rores_app,rores_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
